### ISSUE TITLE
Add support for filtering a config to a specific group

### ISSUE THREAD

**Issue by ocharles** [bos/configurator#2]
Say I have a config like the following:

```
mainDb
{
  database = "foo"
}

thirdPartyDb
{
  database = "
}
```

It would be really nice if I could filter a `Config` down to produce a new `Config`-like object, that only takes about a specific group. My use case is something like:

```
do mainConn <- openConnection (filterConfig appCfg "mainDb")
   thirdPartyConn <- openConnection (filterConfig appCfg "thirdPartyDb")
```

I guess going further this could almost be thought of as wanting lenses into a `Config`, for maximum composability :)

Curious to hear your thoughts!

**Comment by cdsmith** [comment]
It looks like what you want is `subconfig`?  I don't think it's in a released version yet, but it's here in the development version.

**Comment by ocharles** [comment]
Oh sweet, that's exactly what I want :)
