### ISSUE TITLE
Support for Rational configuration values

### ISSUE THREAD

**Issue by basvandijk** [bos/configurator#3]
Hi Bryan,

I would like to use `configurator` but I need to be a able to specify [Rational](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Prelude.html#t:Rational) configuration values.

I see two ways of adding these:
- Change the `Number` constructor from: `Number Integer` to: `Number Number` where the `Number` type will be defined in `attoparsec-text` (or just in `configurator`) and will be similar to the [`Number`](http://hackage.haskell.org/packages/archive/attoparsec/0.9.1.2/doc/html/Data-Attoparsec-Number.html) type from `attoparsec` but uses a `Rational` instead of a `Double`. See [the following](https://gist.github.com/1258740) for an implementation. The following `number` parser should also be defined:

``` haskell
number :: Parser Number
number = floaty $ \real frac fracDenom ->
         if frac == 0 && fracDenom == 0
         then I real
         else R $! asRational real frac fracDenom

asRational :: Integer -> Integer -> Integer -> Rational
asRational real frac fracDenom = real % 1 + frac % fracDenom
```
- Change the `Number` constructor from: `Number Integer` to: `Number Rational`. In the previous solution, if a user wants to check if a number is an integer or a rational she can write a pattern match. In this solution this is still also possible by checking if the [denominator](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Data-Ratio.html#v:denominator) is 1. 

What do you think?

(In my own private code I will go for the latter solution as that is much simpler than the former.)

**Comment by bos** [comment]
Your changes don't compile:

```
Data/Configurator/Parser.hs:87:22:
No instance for (RealFloat Rational)
  arising from a use of `rational'
Possible fix: add an instance declaration for (RealFloat Rational)
In the second argument of `(<$>)', namely `rational'
In the expression: Number <$> rational
In the first argument of `mconcat', namely
  `[string "on" *> pure (Bool True),
    string "off" *> pure (Bool False),
    string "true" *> pure (Bool True),
    string "false" *> pure (Bool False), ....]'
```

**Comment by basvandijk** [comment]
Thanks for merging this Bryan!
